baseURL = "http://localhost:1313"
languageCode =  "pt-BR"
title = "Lucio portfolio"
theme = "hugo-nuo"
publishDir = "docs"
enableRobotsTXT = true
PygmentsCodeFences = true
canonifyurls = true


# Initial site menu, you can extend menu with content.
[[menu.main]]
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"

[[menu.main]]
  name = "Trabalhos"
  weight = 20
  identifier = "works"
  url = "https://github.com/luciojp"

[[menu.main]]
  name = "Tags"
  weight = 30
  identifier = "tags"
  url = "/tags/"

# Add your own params here
[params]
  author = "Antonio Lucio"
  avatar = "/img/avatar.jpg"
  seotitle = "Hugo Blog (SEO Version)"
  subtitle = "~ Analises sobre Boqueirao ~"
  description = ""
  paginate = 10

  # Choose your social networks
  email = "name@domain.com"
  github = "github_username"
  twitter = "twitter_username"
  linkedin = "linkedin_username"
  weibo = "weibo_username"
  wechat= "/img/qrcode.jpg" # Replace with your wechat qrcode image